const englishCopy: Record<string, string> = {
  "# หัวข้อของคุณ…": "# Your heading…",
  "10 แถว": "10 rows",
  "2 ช่อง": "2 spaces",
  "25 แถว": "25 rows",
  "4 ช่อง": "4 spaces",
  "ขยายตัวอย่างหน้า PDF": "Enlarge PDF page preview",
  "จากหน้า": "From page",
  "ถึงหน้า": "To page",
  "ตัวอย่างจะทำงานต่อเมื่อกลับมาที่แท็บนี้": "The preview will resume when you return to this tab.",
  "จำนวนหน้าจะแสดงหลังโหลดตัวอย่าง PDF": "The page count appears after the PDF preview loads.",
  "ช่วงหน้าซ้ำกัน · แก้ไขช่วงที่เลือกก่อนทำต่อ": "Page ranges overlap. Adjust the selected ranges before continuing.",
  "ช่วงเลขหน้าซ้ำกัน · แก้ไขรูปแบบก่อนทำต่อ": "Page number ranges overlap. Adjust the ranges before continuing.",
  "ช่วงหน้าไม่ถูกต้อง · ระบุหน้าตั้งแต่ 1 ถึง": "Invalid page range. Enter pages from 1 to",
  "ช่วงเลขหน้าไม่ถูกต้อง · ระบุหน้า 1 ถึง": "Invalid numbering range. Enter pages from 1 to",
  "ทุกหน้า": "All pages",
  "รูปแบบตัวเลข": "Numbering style",
  "ค่าเริ่มต้น": "Starting value",
  "ดูทุกหน้าแบบขยาย": "Open full-page preview",
  "หน้าตัวอย่าง": "Preview page",
  "ไม่มีเลขหน้าสำหรับหน้านี้": "No page number is set for this page.",
  "หมายเลขหน้าไม่อยู่ในเอกสาร": "That page number is outside this document.",
  "ตำแหน่งลายน้ำ": "Watermark placement",
  "ลากลายน้ำเพื่อย้ายตำแหน่ง": "Drag or click the page to move the watermark. Use arrow keys to fine-tune.",
  "จัดกึ่งกลาง": "Center watermark",
  "ลบไฟล์": "Remove file",
  "ลบรูปแบบนี้": "Remove this rule",
  "ลบช่วงที่": "Remove range",
  "เลือกหน้าเอง": "Choose pages",
  "เลือกช่วงหน้า": "Page ranges",
  "เพิ่มช่วง": "Add range",
  "เพิ่มช่วงรูปแบบ": "Add numbering range",
  "หน้าสุดท้าย": "Last page",
  "หน้าทั้งหมด": "total pages",
  "หน้าเดียว": "Single page",
  "ไปหน้าที่": "Go to page",
  "หน้าที่": "Page",
  "ปิดตัวอย่าง": "Close preview",
  "กำหนดช่วงหน้า": "Set page ranges",
  "กำหนดรูปแบบเลขหน้า": "Set page numbering",
  "กำลังเตรียมตัวอย่างหน้า PDF": "Preparing PDF page previews…",
  "จัดการหน้า PDF": "Manage PDF pages",
  "จัดการไฟล์ PDF": "Manage PDF",
  "จัดการรูปภาพ": "Manage images",
  "แต่ละช่วงจะได้ PDF แยกหนึ่งไฟล์": "Each range creates a separate PDF.",
  "ตัวอย่าง: หน้า 1–3 เป็น ก ข ค และหน้า 4 เป็นต้นไปเป็น 1 2 3": "Example: pages 1–3 use ก ข ค, then page 4 onward uses 1 2 3.",
  "อักษรอังกฤษตัวพิมพ์ใหญ่": "Uppercase letters",
  "อักษรอังกฤษตัวพิมพ์เล็ก": "Lowercase letters",
  "อักษรไทย": "Thai letters",
  "หน้าที่ต้องการแปลง": "Pages to convert",
  "ภาพพร้อมสร้าง PDF": "images ready for PDF",
  "ขนาดตัวอักษร": "Font size",
  "ช่วงที่": "Range",
  "ไฟล์ที่เลือก": "Selected files",
  "รูปแบบนี้": "This style",
  "งานหยุดเมื่อออกจากแท็บหรือหน้าเว็บแล้ว กรุณาเริ่มใหม่": "Processing stopped after you left this tab or page. Run it again to continue.",
  "กรุณาเพิ่มช่วงหน้าที่ต้องการ": "Add at least one page range.",
  "เลขเริ่มต้นต้องเป็นจำนวนเต็มตั้งแต่ 1 ถึง 999999": "The starting value must be a whole number from 1 to 999,999.",
  "50 แถว": "50 rows",
  "A4 ตามแนวภาพ": "A4 landscape",
  "กำลังสร้างตัวอย่าง PDF…": "Rendering PDF preview…",
  "ไม่สามารถแสดงตัวอย่างไฟล์นี้ได้": "Could not preview this file.",
  "ไม่สามารถสร้างตัวอย่างหน้าได้": "Could not render the page previews.",
  "หน้าที่ลากจัดลำดับได้": "Draggable page",
  "ลากหน้าไปยังตำแหน่งใหม่ หรือใช้ปุ่มลูกศรเพื่อเรียงหน้า": "Drag a page to reorder it, or use the arrow buttons.",
  "ลากเพื่อเรียงหน้า หรือหมุนและลบหน้าได้ตามต้องการ": "Drag to reorder pages, or rotate and remove them as needed.",
  "ลากเพื่อเรียงหน้า หรือหมุนและลบหน้าที่ไม่ต้องการก่อนบันทึก": "Drag to reorder, rotate, or remove pages before saving.",
  "ตัวอย่าง PDF": "PDF preview",
  "ตัวอย่าง PDF ที่เลือก": "Selected PDF previews",
  "หน้า PDF": "PDF page",
  "ปรับขนาดภาพ": "Resize image",
  "ลากบนภาพเพื่อเลือกส่วนที่ต้องการครอบ จับตรงกลางเพื่อย้าย หรือจับจุดมุมเพื่อปรับขนาด": "Drag on the image to select a crop. Drag inside it to move, or use a corner to resize.",
  "พื้นที่ครอบภาพ ลากเพื่อเลือกและปรับกรอบ": "Crop area. Drag to select and adjust the frame.",
  "ภาพต้นฉบับสำหรับครอบ": "Original image to crop",
  "ตัวอย่างผลลัพธ์": "Live output preview",
  "ดาวน์โหลดรูปภาพ": "Download image",
  "ตัวอย่าง Favicon": "Favicon preview",
  "ตัวอย่างไอคอน": "Icon preview",
  "ตัวอย่างอักษรย่อ": "Initials preview",
  "BMI โดยประมาณ": "Estimated BMI",
  "Base64 หรือ Data URL": "Base64 or data URL",
  "Cron expression 5 ช่อง": "Five-field cron expression",
  "Decode ไม่ใช่ Verification": "Decoded only, not verified",
  "JSON ถูกต้อง": "Valid JSON",
  "จัดรูปแบบ": "Format",
  "ตรวจ JSON": "Validate JSON",
  "ย่อ JSON": "Minify JSON",
  "ดูเป็นต้นไม้": "Tree view",
  "JSON ที่จัดรูปแบบแล้ว": "Formatted JSON",
  "QR Code ที่สร้างในเบราว์เซอร์": "QR code generated in your browser",
  "all หรือ 1-3, 5": "all or 1-3, 5",
  "all หรือ 1-3,5": "all or 1-3,5",
  "เว้นว่างเพื่ออ่านทุกหน้า เช่น 1-3,5": "Leave blank to read all pages, e.g. 1-3,5",
  "· วางข้อมูลหรือเปิดไฟล์จากอุปกรณ์ของคุณ": "· Paste data or open a file from your device",
  "กรุณาระบุปีเป็นจำนวนเต็มมากกว่า 0": "Enter a year as a whole number greater than 0.",
  "กลับคำ": "Reverse words",
  "กลับตัวอักษร": "Reverse characters",
  "กลับบรรทัด": "Reverse lines",
  "กลับหน้าแรก": "Back to home",
  "กว้าง": "Width",
  "กำลังเปิดเครื่องมือ…": "Opening tool…",
  "กิจกรรมต่อสัปดาห์": "Active days per week",
  "ก่อนหน้า": "Previous",
  "ก่อนแก้ไข": "Before",
  "ขนาดหน้า": "Page size",
  "ข้อความ": "Text",
  "ข้อความจาก PDF": "Text from PDF",
  "ข้อความต้นฉบับ": "Original text",
  "ข้อความทดสอบ": "Test text",
  "ข้อความที่ต้องการค้นหา": "Text to find",
  "ข้อความที่สลับภาษา": "Converted text",
  "ข้อความลายน้ำ": "Watermark text",
  "ข้อความใหม่": "New text",
  "ข้อมูลจะอยู่ในโค้ดที่ดาวน์โหลดและไม่ถูกส่งไปที่ใด": "The data stays in the code you download and is not sent anywhere.",
  "ข้อมูลต้นฉบับ": "Source data",
  "ข้อมูลต้นทาง": "Input data",
  "ข้อมูลร่างกายและกิจกรรม": "Body and activity details",
  "ค.ศ. → พ.ศ.": "CE → BE",
  "ความกว้าง (px)": "Width (px)",
  "ความปลอดภัย": "Security",
  "ความยาว": "Length",
  "ความสูง (px)": "Height (px)",
  "ความแตกต่าง": "Differences",
  "คอลัมน์": "Column",
  "คำ": "Words",
  "คำนวณ VAT จากยอดรวมค่าบริการ แล้วบวกทิปจากยอดก่อนค่าบริการ": "VAT is calculated on the subtotal plus service charge; tip is based on the subtotal.",
  "คำนวณช่วงเวลา": "Calculate duration",
  "คำอ่านภาษาไทย": "Thai pronunciation",
  "ค่า": "Value",
  "ค่าที่กรอกไม่ถูกต้องสำหรับฐาน": "This value is invalid for the selected base.",
  "ค่าบริการ": "Service charge",
  "ค่าบริการ (%)": "Service charge (%)",
  "ค้นหา": "Search",
  "ค้นหาทุกคอลัมน์": "Search all columns",
  "ค้นหาและแทนที่": "Find and replace",
  "งานที่ต้องการทำ": "Task",
  "จาก": "From",
  "จำนวน": "Quantity",
  "จำนวน UUID v4": "Number of UUID v4s",
  "จำนวนคน": "Number of people",
  "จำนวนช่องว่าง": "Number of spaces",
  "จำนวนรายการ": "Number of items",
  "จำนวนเงิน": "Amount",
  "ชนิดข้อมูล": "Data type",
  "ชั่วโมง": "Hours",
  "ชาย": "Male",
  "ชื่อเครือข่าย (SSID)": "Network name (SSID)",
  "ช่วงหน้า · ใช้ ; คั่นแต่ละไฟล์": "Page ranges · separate each file with ;",
  "ฐานข้อมูลเข้า": "Input base",
  "ดาวน์โหลด": "Download",
  "ดาวน์โหลด PNG": "Download PNG",
  "ดาวน์โหลดผลลัพธ์": "Download result",
  "ดึงข้อความ": "Extract text",
  "ด้านยาวสูงสุด (px)": "Longest edge (px)",
  "ตัวจับเวลาโฟกัส": "Focus timer",
  "ตัวอย่าง": "Preview",
  "ตัวอย่าง 1-3; 4-6 จะได้ PDF 2 ไฟล์": "Example: 1-3; 4-6 creates two PDF files.",
  "ตัวอย่างจะแสดงที่นี่": "Your preview will appear here.",
  "ตัวอักษร": "Characters",
  "ตัวเลข": "Numbers",
  "ตัวเลือก flags": "Flag options",
  "ตั้งค่าเวลา": "Set time",
  "ตารางตัวอย่างแสดง 200 แถวแรก แต่ไฟล์ส่งออกมีครบ": "The preview shows the first 200 rows; exports include all rows.",
  "ตำแหน่ง": "Position",
  "ต่ำสุด": "Minimum",
  "ต้นฉบับ": "Original",
  "ถัดไป": "Next",
  "ทดสอบ": "Test",
  "ทำครบ": "Complete all",
  "ทำรายการไม่สำเร็จ": "Could not complete the task.",
  "ทิป": "Tip",
  "ทิป (%)": "Tip (%)",
  "ทิศทาง": "Direction",
  "นำเข้า JSON": "Import JSON",
  "น้อย → มาก": "Low → high",
  "น้อยมาก": "Very light",
  "น้ำหนัก": "Weight",
  "น้ำหนัก (กก.)": "Weight (kg)",
  "บนกลาง": "Top center",
  "บนขวา": "Top right",
  "บนซ้าย": "Top left",
  "บรรทัด": "Lines",
  "บันทึก PDF ที่จัดแล้ว": "Save organized PDF",
  "ประมวลผลรูปภาพ": "Process image",
  "ประเภท": "Type",
  "ปานกลาง 3–5 วัน": "Moderate, 3–5 days",
  "ผลลัพธ์": "Result",
  "ผลลัพธ์จะแสดงที่นี่": "Your result will appear here.",
  "ผลลัพธ์รูปภาพ": "Image result",
  "พ.ศ. → ค.ศ.": "BE → CE",
  "พบ": "Found",
  "พลังงานต่อวันโดยประมาณ": "Estimated daily energy",
  "พอดีกับภาพ": "Fit to image",
  "พัก": "Break",
  "พัก (นาที)": "Break (minutes)",
  "พิมพ์คำที่ต้องการค้นหา...": "Type to search…",
  "พื้นที่": "Area",
  "มาก → น้อย": "High → low",
  "ยอดก่อนเพิ่ม": "Subtotal",
  "ยอดบิลและจำนวนคน": "Bill and people",
  "ยอดรวม": "Total",
  "ยอดอาหารและเครื่องดื่ม (บาท)": "Food and drink total (THB)",
  "ยังไม่มีรายการ": "No items yet.",
  "ย่อหน้า": "Paragraphs",
  "รวมและดาวน์โหลด PDF": "Merge and download PDF",
  "รหัสผ่าน": "Password",
  "รองรับ CSV, TSV และ JSON array · ไฟล์อ่านในเบราว์เซอร์": "Supports CSV, TSV, and JSON arrays · files are read in your browser",
  "รอบ": "Rounds",
  "ระยะทาง": "Distance",
  "รายการ": "Items",
  "รายการของฉัน": "My checklist",
  "รายการอยู่ในหน้านี้ชั่วคราว ปิดหน้าแล้วรายการจะหายไป": "Items stay on this page and are cleared when you leave.",
  "รายการใหม่": "New item",
  "รูปภาพจาก Base64": "Image from Base64",
  "รูปภาพต้นฉบับ": "Original image",
  "รูปภาพมีขนาดเกินขีดจำกัดที่รองรับ กรุณาใช้ข้อมูลรูปที่เล็กกว่า": "This image is larger than the supported limit. Choose a smaller image.",
  "รูปแบบ": "Format",
  "รูปแบบและ flags": "Pattern and flags",
  "ลดขนาดและดาวน์โหลด": "Compress and download",
  "ลบ": "Remove",
  "ลบรายการที่เสร็จแล้ว": "Remove completed items",
  "ลบหน้า": "Delete page",
  "ลำดับ": "Order",
  "ลิงก์": "Link",
  "ล็อกอัตราส่วนภาพ": "Lock aspect ratio",
  "ล่างกลาง": "Bottom center",
  "ล่างขวา": "Bottom right",
  "ล่างซ้าย": "Bottom left",
  "ล้าง": "Clear",
  "วัน": "Days",
  "วันสิ้นสุด": "End date",
  "วันเริ่มต้น": "Start date",
  "วันเวลาหรือ Timestamp": "Date, time, or timestamp",
  "วันและเวลา": "Date & time",
  "วาง CSV, TSV หรือ JSON array ที่นี่…": "Paste a CSV, TSV, or JSON array here…",
  "วาง HTML หรือข้อความที่ต้องการล้าง…": "Paste HTML or text to clean…",
  "วางข้อความทีละบรรทัด…": "Paste one line at a time…",
  "วางข้อความที่ต้องการแก้ไข…": "Paste text to edit…",
  "วางข้อความที่นี่…": "Paste text here…",
  "วางข้อความที่มีบรรทัดว่าง…": "Paste text with blank lines…",
  "วางข้อมูล": "Paste data",
  "วางรายการทีละบรรทัด…": "Paste one item per line…",
  "วิธีนี้ลดขนาดได้มาก แต่ข้อความจะกลายเป็นภาพและค้นหาหรือคัดลอกไม่ได้ เหมาะกับไฟล์สำหรับส่งหรืออ่าน": "This can greatly reduce file size, but turns text into images that cannot be searched or copied. Best for sharing or reading.",
  "สร้าง Hash": "Generate hash",
  "สร้าง Hash จากไฟล์": "Hash file",
  "สร้าง QR Code": "Generate QR code",
  "สร้าง UUID v4": "Generate UUID v4",
  "สร้างชุด Favicon": "Generate favicon set",
  "สร้างรหัสผ่าน": "Generate password",
  "สร้างและดาวน์โหลด PDF": "Create and download PDF",
  "สร้างใหม่": "Generate again",
  "สำหรับหน้าสุดท้าย": "For the last page",
  "สำหรับเลขหน้า และ": "For page numbers and",
  "สี": "Color",
  "สีพื้นหลัง": "Background color",
  "สุ่มตัวเลข": "Generate random numbers",
  "สุ่มลำดับ": "Shuffle order",
  "สูง": "High",
  "สูงสุด": "Maximum",
  "สูตรคำนวณ": "Calculation method",
  "ส่งออก JSON": "Export JSON",
  "ส่วนสูง (ซม.)": "Height (cm)",
  "หญิง": "Female",
  "หนัก 6–7 วัน": "Hard, 6–7 days",
  "หนักมาก": "Very hard",
  "หน่วย": "Unit",
  "หน้า": "Page",
  "หน้าที่ต้องการ": "Pages to keep",
  "หน้าที่ต้องการอ่าน": "Pages to read",
  "หน้าเดิม": "Original page",
  "หมุนขวา": "Rotate right",
  "หมุนซ้าย": "Rotate left",
  "หรือเลือกไฟล์ (สูงสุด": "Or choose a file (up to",
  "หลังแก้ไข": "After",
  "อักษรย่อ (ใช้เมื่อไม่เลือกรูป)": "Initials (used when no image is selected)",
  "อายุ (ปี) — 18 ปีขึ้นไป": "Age (years) — 18 and older",
  "อุณหภูมิ": "Temperature",
  "เครื่องมือนี้อ่านข้อมูลเท่านั้น ไม่ตรวจลายเซ็นและไม่ควรใช้ตัดสินความน่าเชื่อถือของ token": "This tool only decodes data. It does not verify signatures and should not be used to judge whether a token is trustworthy.",
  "เช่น 1,250.50": "e.g. 1,250.50",
  "เช่น l;ylfu หรือ สวัสดี…": "e.g. l;ylfu or hello…",
  "เดือน": "Months",
  "เบา 1–3 วัน": "Light, 1–3 days",
  "เปิดไฟล์": "Open file",
  "เป็น": "To",
  "เพิ่ม": "Add",
  "เพิ่มรายการ": "Add item",
  "เพิ่มรายการ หรือเลือกไฟล์ JSON ที่ต้องการนำเข้า": "Add an item or choose a JSON file to import.",
  "เพิ่มรายการที่ต้องทำ…": "Add a task…",
  "เริ่มช่วงนี้ใหม่": "Restart this session",
  "เริ่มพิมพ์หรือวางข้อความ…": "Start typing or paste text…",
  "เรียง key A–Z": "Sort keys A–Z",
  "เลขเริ่มต้น": "Starting number",
  "เลือก JPG, PNG หรือ WebP": "Choose a JPG, PNG, or WebP image",
  "เลือก PDF ที่ต้องการรวม": "Choose PDFs to merge",
  "เลือก PDF ที่ต้องการลดขนาด": "Choose a PDF to compress",
  "เลือก PDF ที่ต้องการแปลง": "Choose a PDF to convert",
  "เลือก PDF ที่ต้องการแยก": "Choose a PDF to split",
  "เลือก PDF ที่มีชั้นข้อความ": "Choose a PDF with a text layer",
  "เลือก PDF สำหรับใส่ลายน้ำ": "Choose a PDF to watermark",
  "เลือก PDF สำหรับใส่เลขหน้า": "Choose a PDF to add page numbers",
  "เลือก PDF เพื่อจัดหน้า": "Choose a PDF to organize",
  "เลือก PDF เพื่อดูข้อมูล": "Choose a PDF to inspect",
  "เลือกข้อมูลสำหรับ QR Code": "Choose data for the QR code",
  "เลือกประเภทและหน่วย": "Choose a type and unit",
  "เลือกหรือลากรูปภาพมาที่นี่": "Choose or drag an image here",
  "เลือกแล้ว:": "Selected:",
  "เลื่อนขึ้น": "Move up",
  "เลื่อนลง": "Move down",
  "จัดเรียง": "Order",
  "หมุน": "Rotate",
  "ขึ้น": "Up",
  "ลง": "Down",
  "ซ้าย": "Left",
  "ขวา": "Right",
  "เล่นเสียงสั้น ๆ เมื่อจบช่วง": "Play a short sound when each session ends",
  "เวลาปัจจุบัน": "Current time",
  "เวลาอ่าน": "Reading time",
  "เสร็จแล้ว": "Done",
  "แถว": "Rows",
  "แทนที่ด้วย": "Replace with",
  "แปลงข้อมูล": "Convert data",
  "แปลงปี พ.ศ. และ ค.ศ.": "Convert Buddhist Era and Common Era years",
  "แปลงเป็น JPG": "Convert to JPG",
  "แยกตัวพิมพ์เล็ก-ใหญ่": "Match case",
  "แสดงตำแหน่งแรก 100 รายการ": "Showing the first 100 matches",
  "โครงสร้าง JSON": "JSON structure",
  "โทรศัพท์": "Phone",
  "โปรดทราบ": "Please note",
  "โฟกัส": "Focus",
  "โฟกัส (นาที)": "Focus (minutes)",
  "โหมดข้อมูล": "Data mode",
  "ใช้": "Use",
  "ใช้สูตรประเมินสำหรับผู้ใหญ่อายุ 18 ปีขึ้นไปเท่านั้น ไม่ใช้ประเมินวัยรุ่นหรือแทนคำแนะนำจากบุคลากรสุขภาพ": "This estimate is for adults aged 18 and older only. It is not for teenagers and does not replace advice from a health professional.",
  "ใส่ข้อความทั้งสองฝั่งเพื่อเปรียบเทียบ": "Enter text on both sides to compare.",
  "ใส่ลายน้ำและดาวน์โหลด": "Add watermark and download",
  "ใส่เลขหน้าและดาวน์โหลด": "Add page numbers and download",
  "ไทย": "Thai",
  "ไปยัง": "Go to",
  "ไฟล์จะถูกอ่านและประมวลผลในเบราว์เซอร์": "Files are read and processed in your browser.",
  "ไม่พบข้อมูลที่ตรงกับเงื่อนไข": "No matching data found.",
  "ไม่พบข้อมูลรูปภาพ PNG, JPEG หรือ WebP Base64 ที่ถูกต้อง": "No valid PNG, JPEG, or WebP Base64 image data found.",
  "ไม่พบหน้าที่ต้องการ": "Page not found",
  "ไม่มีรหัสผ่าน": "No password",
  "ไม่รวมช่องว่าง": "Without spaces",
  "ไม่ให้ตัวเลขซ้ำ": "No repeated numbers",
  "คัดลอก": "Copy",
  "คัดลอกแล้ว": "Copied",
  "นาที": "minutes",
  "พิมพ์รายการก่อนเพิ่มลง Checklist": "Enter a task before adding it.",
  "ลบรายการ": "Remove item",
  "ทำเครื่องหมายว่ายังไม่เสร็จ": "Mark as not done",
  "ทำเครื่องหมายว่าเสร็จแล้ว": "Mark as done",
  "รายการต้องมีความยาวไม่เกิน 500 ตัวอักษร": "Tasks must be 500 characters or fewer.",
  "Checklist มีได้ไม่เกิน 500 รายการ": "A checklist can contain up to 500 items.",
  "นำเข้า Checklist ไม่สำเร็จ": "Could not import the checklist.",
  "ดาวน์โหลด Checklist JSON แล้ว": "Checklist JSON downloaded.",
  "ไฟล์ JSON อ่านไม่ได้ กรุณาตรวจรูปแบบแล้วลองนำเข้าอีกครั้ง": "Could not read this JSON file. Check its format and try again.",
  "ไฟล์นี้ไม่ใช่ Checklist JSON เวอร์ชัน 1": "This file is not a version 1 Checklist JSON file.",
  "ไฟล์นี้ว่างเปล่า กรุณาเลือกไฟล์อื่น": "This file is empty. Choose another file.",
  "ไฟล์ Checklist ต้องมีขนาดไม่เกิน 1 MB": "Checklist files must be 1 MB or smaller.",
  "รองรับเฉพาะไฟล์ .json": "Only .json files are supported.",
  "ไม่สามารถประมวลผลข้อมูลนี้ได้": "Could not process this data.",
  "สร้าง Hash ไม่สำเร็จ": "Could not generate the hash.",
  "อ่านไฟล์หรือสร้าง Hash ไม่สำเร็จ": "Could not read the file or generate the hash.",
  "สร้าง Favicon ไม่สำเร็จ": "Could not generate the favicon.",
  "ไม่สามารถเปิดรูปภาพนี้ได้": "Could not open this image.",
  "เบราว์เซอร์ไม่รองรับ Canvas": "This browser does not support Canvas.",
  "สร้างไฟล์รูปภาพไม่สำเร็จ": "Could not create the image file.",
  "Canvas ไม่พร้อมใช้งาน": "Canvas is unavailable.",
  "ไฟล์มีขนาดเกินขีดจำกัดที่รองรับ กรุณาใช้ข้อมูลรูปที่เล็กกว่า": "This image exceeds the supported size. Choose a smaller image.",
  "ทุกช่วงหน้าต้องมีหมายเลขหน้า เช่น 1-3; 4-6": "Enter a page range for each file, for example 1-3; 4-6.",
  "กรุณาเลือกไฟล์ PDF": "Choose a PDF file.",
  "กรุณาเลือก PDF": "Choose a PDF.",
  "ต้องเหลืออย่างน้อย 1 หน้า": "Keep at least one page.",
  "ช่วงหน้าไม่ถูกต้อง ใช้ ; คั่นไฟล์ เช่น 1-3; 4-6": "The page ranges are invalid. Separate files with ;, for example 1-3; 4-6.",
  "ช่วงหน้าไม่ถูกต้อง": "The page range is invalid.",
  "รูปแบบเลขหน้ารองรับตัวอักษรอังกฤษและตัวเลขเท่านั้น": "Page number formats support English letters and numbers only.",
  "กรุณาเลือกไฟล์และใส่ข้อความ": "Choose a file and enter text.",
  "กรุณาระบุหมายเลขหน้า": "Enter a page number.",
  "กรุณาระบุจำนวนเงินเป็นตัวเลข เช่น 1250.50": "Enter an amount as a number, for example 1250.50.",
  "เครื่องหมายจุลภาคต้องคั่นหลักพัน เช่น 1,250.50": "Commas must separate thousands, for example 1,250.50.",
  "จำนวนสตางค์ต้องมีไม่เกิน 2 หลัก": "Amounts can have at most two decimal places.",
  "YAML ไม่ถูกต้อง กรุณาตรวจ indentation, colon และเครื่องหมายคำพูด": "Invalid YAML. Check indentation, colons, and quotation marks.",
  "Base64 ไม่ถูกต้อง หรือข้อมูลไม่ใช่ข้อความ UTF-8": "Invalid Base64 or the data is not UTF-8 text.",
  "URL ไม่ถูกต้อง กรุณาใส่ URL ที่มี protocol เช่น https://example.com": "Invalid URL. Include a protocol, such as https://example.com.",
  "URL encoding ไม่ถูกต้อง กรุณาตรวจรูปแบบ %xx แล้วลองอีกครั้ง": "Invalid URL encoding. Check the %xx sequences and try again.",
  "JSON สำหรับ Query ไม่ถูกต้อง กรุณาตรวจวงเล็บและ comma": "Invalid query JSON. Check the brackets and commas.",
  "ใส่ JSON array ของรายการ key และ value เช่น [{\"key\":\"q\",\"value\":\"คำค้น\"}]": "Enter a JSON array of key/value pairs, for example [{\"key\":\"q\",\"value\":\"search term\"}].",
  "รูปแบบวันเวลาหรือ timestamp ไม่ถูกต้อง": "Invalid date, time, or timestamp format.",
  "วันเวลาที่ระบุไม่ถูกต้อง": "The specified date and time is invalid.",
  "ไม่รู้จักเขตเวลานี้ กรุณาเลือกเขตเวลา IANA เช่น Asia/Bangkok": "Unknown time zone. Choose an IANA zone such as Asia/Bangkok.",
  "กรุณาระบุวันและเวลาให้ครบ": "Enter both the date and time.",
  "วันหรือเวลาที่ระบุไม่มีอยู่จริง": "That date or time does not exist.",
  "เวลานี้ไม่มีอยู่ในเขตเวลานั้น กรุณาเลือกเวลาอื่น": "This time does not exist in that time zone. Choose another time.",
  "กรุณาระบุวันที่ให้ครบ": "Enter a complete date.",
  "วันที่ที่ระบุไม่มีอยู่จริง": "That date does not exist.",
  "กรุณาระบุตัวเลขที่ต้องการแปลง": "Enter a number to convert.",
  "อุณหภูมิต่ำกว่าศูนย์เคลวินไม่ได้": "Temperature cannot be below absolute zero.",
  "เลือกหน่วยต้นทางและปลายทางให้ถูกต้อง": "Choose valid source and target units.",
  "ตรวจยอดเงินและจำนวนคนอีกครั้ง": "Check the amount and number of people.",
  "เปอร์เซ็นต์ต้องอยู่ระหว่าง 0 ถึง 100": "Percentages must be between 0 and 100.",
  "กรอกอายุ 18 ปีขึ้นไป น้ำหนัก ส่วนสูง และระดับกิจกรรมให้ถูกต้อง": "Enter a valid age of 18 or older, weight, height, and activity level.",
  "Regular Expression ต้องยาวไม่เกิน 250 ตัวอักษร": "Regular expressions must be 250 characters or fewer.",
  "ข้อความทดสอบต้องไม่เกิน 20,000 ตัวอักษร": "Test text must be 20,000 characters or fewer.",
  "กรุณาใส่ Regular Expression": "Enter a regular expression.",
  "Regular Expression หรือ flags ไม่ถูกต้อง ตรวจวงเล็บและอักขระพิเศษ": "Invalid regular expression or flags. Check brackets and special characters.",
  "กรุณาใส่ข้อความก่อนสร้าง QR Code": "Enter text before creating a QR code.",
  "กรุณาใส่ URL ที่ถูกต้อง เช่น https://example.com": "Enter a valid URL, such as https://example.com.",
  "รองรับเฉพาะ URL ที่ขึ้นต้นด้วย http หรือ https": "Only URLs starting with http or https are supported.",
  "กรุณาใส่หมายเลขโทรศัพท์ที่ถูกต้อง": "Enter a valid phone number.",
  "กรุณาใส่ชื่อเครือข่าย Wi-Fi": "Enter a Wi-Fi network name.",
  "JWT ต้องมีอย่างน้อย 2 ส่วน": "A JWT must contain at least two parts.",
  "JWT ไม่ถูกต้อง": "Invalid JWT.",
  "JSON ต้องเป็น array of objects": "JSON must be an array of objects.",
  "JSON ต้องเป็น array": "JSON must be an array.",
  "ค่าสูงสุดต้องมากกว่าหรือเท่ากับค่าต่ำสุด": "The maximum must be greater than or equal to the minimum.",
  "ช่วงตัวเลขมีไม่พอสำหรับค่าที่ไม่ซ้ำ": "The range does not contain enough unique numbers.",
  "สุ่มตัวเลขไม่สำเร็จ": "Could not generate random numbers.",
  "เปิดไฟล์ไม่สำเร็จ": "Could not open the file.",
  "รองรับเฉพาะไฟล์ CSV, TSV, TXT หรือ JSON": "Only CSV, TSV, TXT, or JSON files are supported.",
  "CSV มีข้อมูลต่อท้ายเครื่องหมายคำพูดที่ปิดแล้ว": "CSV contains data after a closing quotation mark.",
  "CSV มีเครื่องหมายคำพูดอยู่กลางช่องข้อมูล": "CSV contains a quotation mark inside an unquoted field.",
  "CSV มีเครื่องหมายคำพูดที่ยังไม่ปิด": "CSV contains an unclosed quotation mark.",
  "อ่านข้อมูลที่เลือกไม่สำเร็จ": "Could not read the selected data.",
  "ไม่สามารถประมวลผลไฟล์นี้ได้": "Could not process this file.",
  "รูปแบบรายการไม่ถูกต้อง": "Invalid item format.",
  "กรุณาเลือกไฟล์อื่น": "Choose another file.",
  "ไม่สามารถสร้างรหัสผ่านได้": "Could not generate a password.",
  "สร้าง QR Code ไม่สำเร็จ": "Could not generate the QR code.",
  "กรุณาระบุ URL ที่ถูกต้อง": "Enter a valid URL.",
  "รูปแบบไฟล์ไม่รองรับ": "Unsupported file format.",
  "อัปโหลดไฟล์ไม่สำเร็จ": "Could not load the file.",
  "ข้อมูลไม่ถูกต้อง": "Invalid data.",
  "ไฟล์ไม่ถูกต้อง": "Invalid file.",
  "ไฟล์ชนิดหรือขนาดไม่รองรับ": "Unsupported file type or size.",
  "อ่านไฟล์รูปภาพไม่สำเร็จ": "Could not read the image file.",
  "อ่านรูปภาพไม่สำเร็จ": "Could not read the image.",
  "ประมวลผลรูปภาพไม่สำเร็จ": "Could not process the image.",
  "สร้าง Favicon 6 ขนาดและดาวน์โหลด ZIP แล้ว": "Created six favicon sizes and downloaded the ZIP.",
  "คำนวณเวลาไม่สำเร็จ": "Could not calculate the time.",
  "ตรวจ Regular Expression ไม่สำเร็จ": "Could not test the regular expression.",
  "JSON ต้องเป็น array of objects เช่น [{\"name\":\"Ada\"}]": "JSON must be an array of objects, for example [{\"name\":\"Ada\"}].",
  "ไม่สามารถแปลงข้อมูลได้": "Could not convert the data.",
  "วันที่": "day of month",
  "วันในสัปดาห์": "day of week",
  "สุ่ม": "Random",
  "สัญลักษณ์": "Symbols",
  "รวมอักขระคล้ายกัน": "Include similar-looking characters",
  "ไม่เลือกรูปก็สร้างจากอักษรย่อได้": "You can generate one from initials without an image.",
  "ตัวอักษรทั้งหมด": "All characters",
  "ไฟล์พร้อมใช้งาน": "files ready",
  "จัดเรียงหน้าก่อนรวม": "Arrange pages before merging",
  "เปิดเพื่อย้ายและจัดลำดับหน้าข้ามไฟล์ PDF ได้": "Turn this on to move and reorder pages across PDFs.",
  "ลำดับหน้าของไฟล์ที่จะรวม": "Page order in the merged PDF",
  "หน้าสำหรับไฟล์รวม": "pages in the merged PDF",
  "ไฟล์ในชุด": "files in this set",
  "ลำดับผลลัพธ์": "Output order",
  "ลากหน้าหรือใช้ปุ่มขึ้นลงเพื่อจัดลำดับข้ามไฟล์": "Drag pages or use the up and down buttons to reorder across files.",
  "ไม่สามารถแสดงตัวอย่าง PDF ได้": "Could not preview this PDF.",
  "ไม่พบไฟล์ต้นฉบับของหน้าที่เลือก": "Could not find the source file for a selected page.",
  "เพิ่ม PDF": "Add PDFs",
  "ไฟล์อยู่บนอุปกรณ์ของคุณตลอดการทำงาน": "Files stay on your device.",
  "อ่านเฉพาะข้อมูลภายในไฟล์บนอุปกรณ์ของคุณ": "Only metadata from this file is read on your device.",
  "พิมพ์คำค้นหาเพื่อดูจำนวนตำแหน่งที่พบ": "Type a search term to see the number of matches.",
  "รวมไฟล์": "Merge files",
  "แยกหน้า": "Split pages",
  "จัดลำดับหน้า": "Reorder pages",
  "หมุนหน้า": "Rotate pages",
  "ลดขนาด": "Compress",
  "PDF เป็น JPG": "PDF to JPG",
  "รูปภาพเป็น PDF": "Images to PDF",
  "คัดลอกข้อความ": "Extract text",
  "ดูข้อมูล PDF": "View PDF details",
  "ดู ค้นหา และเรียง CSV": "View, search, and sort CSV",
  "CSV เป็นตาราง": "CSV to table",
  "ลบแถวซ้ำ": "Remove duplicate rows",
  "เรียงตาราง": "Sort table",
  "กรองตาราง": "Filter table",
  "แยกคอลัมน์": "Extract column",
  "ตารางเป็น JSON": "Table to JSON",
  "ตารางเป็น CSV": "Table to CSV",
  "พบอักขระที่ไม่รองรับใน cron expression": "The cron expression contains unsupported characters.",
  "ทำงานทุกวัน": "Runs every day",
  "ทำงานวันจันทร์ถึงศุกร์ เวลา 09:00": "Runs Monday to Friday at 09:00",
  "แข็งแรงมาก": "Very strong",
  "แข็งแรง": "Strong",
  "ปานกลาง": "Medium",
  "ควรเพิ่มความยาวหรือตัวเลือก": "Consider adding length or more character types.",
  "อ่านข้อมูลสำเร็จ": "Data read successfully",
  "กำลังเตรียมไฟล์...": "Preparing file…",
  "กำลังอ่านรูปภาพ...": "Reading image…",
  "กำลังประมวลผลบนอุปกรณ์ของคุณ...": "Processing on your device…",
  "แปลงเวลาไม่สำเร็จ": "Could not convert the time.",
  "แปลงเขตเวลาไม่สำเร็จ": "Could not convert the time zone.",
  "คำนวณยอดไม่สำเร็จ": "Could not calculate the bill.",
  "คำนวณไม่สำเร็จ": "Could not calculate the result.",
  "แปลงหน่วยไม่สำเร็จ": "Could not convert the unit.",
  "วางข้อมูลที่นี่…": "Paste your data here…",
  "กำลังแปลง…": "Converting…",
  "หรือเลือกไฟล์ (สูงสุด ": "Or choose a file (up to ",
  "เลือกแล้ว: ": "Selected: ",
  "พบ ": "Found ",
  "ค่าที่กรอกไม่ถูกต้องสำหรับฐาน ": "This value is invalid for base ",
  "ทำครบ ": "Completed ",
  "ผลลัพธ์ ": "Results ",
  "หน้า ": "Page ",
  "ตารางตัวอย่างแสดง 200 แถวแรก แต่ไฟล์ส่งออกมีครบ ": "The preview shows the first 200 rows; exports contain all ",
  "ข้อความจาก PDF ": "Text from PDF ",
  "หน้าเดิม ": "Original page ",
  "ใช้ ": "Use ",
  "สำหรับเลขหน้า และ ": "for page numbers and ",
  "เวลาไทย": "Thailand time",
  "จำนวนหน้า": "Page count",
  "ชื่อเรื่อง": "Title",
  "ผู้เขียน": "Author",
  "หัวข้อ": "Subject",
  "วันที่สร้าง": "Created",
  "วันที่แก้ไข": "Modified",
  "เข้ารหัส": "Encrypted",
  "ใช่": "Yes",
  "ไม่": "No",
  "รูปแบบรายการ": "Item format",
  "ปี พ.ศ.": "Buddhist Era year (BE)",
  "ปี ค.ศ.": "Common Era year (CE)",
  "ช่วงโฟกัส": "Focus session",
  "ช่วงพัก": "Break session",
  "พักชั่วคราว": "Pause",
  "เริ่มจับเวลา": "Start timer",
  "ตัวอย่างทุกหน้าสร้างบนอุปกรณ์ของคุณ": "Page previews are created on your device.",
  "เพิ่มได้หลายไฟล์ · เรียงลำดับก่อนดาวน์โหลด": "Add multiple files · reorder before downloading.",
  "ไฟล์ผลลัพธ์หลายรายการจะดาวน์โหลดเป็น ZIP": "Multiple output files download as a ZIP.",
  "ใช้การแปลงแต่ละหน้าเป็นภาพใหม่บนอุปกรณ์ของคุณ": "Each page is rebuilt as a new image on your device.",
  "หลายหน้าจะดาวน์โหลดเป็น ZIP": "Multiple pages download as a ZIP.",
  "เรียงตามลำดับด้านล่าง · หนึ่งภาพต่อหนึ่งหน้า": "Images are added in the order shown, one per page.",
  "รองรับเอกสารทุกขนาดหน้า": "Works with pages of any size.",
  "ข้อความภาษาไทยและอังกฤษจะถูกสร้างเป็นภาพโปร่งใส": "Thai and English text is rendered as a transparent image.",
  "ใช้ลูกศรเพื่อเรียงหน้าใหม่": "Use the arrows to reorder pages.",
  "หมุนแต่ละหน้าได้อิสระ และยังเรียงหรือลบได้": "Rotate each page independently, and reorder or remove pages.",
  "ลบหน้าที่ไม่ต้องการ และยังเรียงหรือหมุนได้ก่อนบันทึก": "Remove unwanted pages, then reorder or rotate pages before saving.",
  "แยกทุกหน้าเป็น ZIP": "Split every page into a ZIP",
  "แยกและดาวน์โหลด": "Split and download",
  "รองรับเฉพาะไฟล์ PDF กรุณาเลือกไฟล์ .pdf": "Only PDF files are supported. Choose a .pdf file.",
  "รองรับเฉพาะ JPG, PNG และ WebP กรุณาเลือกไฟล์ชนิดที่รองรับ": "Only JPG, PNG, and WebP images are supported.",
  "Cron ต้องมี 5 ช่อง: นาที ชั่วโมง วันที่ เดือน วันในสัปดาห์": "Cron must have five fields: minute, hour, day of month, month, and day of week.",
  "ค่าบางช่องอยู่นอกช่วงที่รองรับ: นาที 0–59, ชั่วโมง 0–23, วันที่ 1–31, เดือน 1–12, วัน 0–7": "One or more fields are outside the supported ranges: minute 0–59, hour 0–23, day 1–31, month 1–12, weekday 0–7.",
  "ช่วง": "Sessions",
  "มีรายการครบ": "Complete",
};

export function uiText(value: string): string {
  const language = document.documentElement.dataset.language;
  if (language === "th") return value;

  const normalized = value.replace(/\s+/g, " ");
  const leading = normalized.startsWith(" ") ? " " : "";
  const trailing = normalized.endsWith(" ") ? " " : "";
  const key = normalized.trim();
  const direct = englishCopy[key];
  if (direct) return leading + direct + trailing;
  const patterns: Array<[RegExp, (match: RegExpMatchArray) => string]> = [
    [/^นำเข้าแล้ว (\d+) รายการ$/, (match) => `Imported ${match[1]} items.`],
    [/^ไฟล์มีขนาดเกิน (.+) MB$/, (match) => `File exceeds the ${match[1]} MB size limit.`],
    [/^ไฟล์มีขนาดเกิน (.+) MB กรุณาเลือกไฟล์ที่เล็กกว่า$/, (match) => `File exceeds the ${match[1]} MB size limit. Choose a smaller file.`],
    [/^ทุกไฟล์ต้องมีหมายเลขหน้า เช่น 1-3; 4-6$/, () => "Enter page ranges for each file, for example 1-3; 4-6."],
    [/^รูปแบบรายการที่ (\d+) ไม่ถูกต้อง$/, (match) => `Item ${match[1]} has an invalid format.`],
    [/^นำเข้าได้ไม่เกิน (\d+) รายการต่อครั้ง$/, (match) => `Import up to ${match[1]} items at a time.`],
    [/^ช่วงหน้า “(.+)” ไม่ถูกต้อง$/, (match) => `Invalid page range “${match[1]}”.`],
    [/^หน้าต้องอยู่ระหว่าง 1-(\d+)$/, (match) => `Page numbers must be between 1 and ${match[1]}.`],
    [/^JSON ไม่ถูกต้อง(.*) กรุณาตรวจวงเล็บ เครื่องหมายคำพูด และ comma$/, (match) => `Invalid JSON${match[1]}. Check brackets, quotation marks, and commas.`],
    [/^ไฟล์มีขนาดเกิน (\d+) MB$/, (match) => `File exceeds the ${match[1]} MB size limit.`],
    [/^พบ (\d+) รายการ$/, (match) => `${match[1]} matches found.`],
    [/^ทุกไฟล์ต้องมีหมายเลขหน้า เช่น 1-3; 4-6$/, () => "Enter page ranges for every file, for example 1-3; 4-6."],
    [/^กำลังอ่านหน้า (\d+) จาก (\d+)$/, (match) => `Reading page ${match[1]} of ${match[2]}…`],
    [/^กำลังรวม (.+)$/, (match) => `Merging ${match[1]}…`],
    [/^กำลังสร้างไฟล์ (\d+) จาก (\d+)$/, (match) => `Creating file ${match[1]} of ${match[2]}…`],
    [/^กำลังบีบอัดหน้า (\d+) จาก (\d+)$/, (match) => `Compressing page ${match[1]} of ${match[2]}…`],
    [/^กำลังแปลงหน้า (\d+) จาก (\d+)$/, (match) => `Converting page ${match[1]} of ${match[2]}…`],
    [/^กำลังเพิ่มภาพ (\d+) จาก (\d+)$/, (match) => `Adding image ${match[1]} of ${match[2]}…`],
    [/^กำลังสร้างตัวอย่างหน้า (\d+) จาก (\d+)$/, (match) => `Rendering preview for page ${match[1]} of ${match[2]}…`],
    [/^ข้อความหน้า PDF ดึงสำเร็จ (\d+) หน้า$/, (match) => `Extracted text from ${match[1]} PDF pages.`],
    [/^ช่วงหน้าไม่ถูกต้อง · ระบุหน้าตั้งแต่ 1 ถึง (\d+)$/, (match) => `Invalid page range. Enter pages from 1 to ${match[1]}.`],
    [/^ช่วงเลขหน้าไม่ถูกต้อง · ระบุหน้า 1 ถึง (\d+)$/, (match) => `Invalid numbering range. Enter pages from 1 to ${match[1]}.`],
    [/^นำเข้าแล้ว (\d+) รายการ$/, (match) => `Imported ${match[1]} items.`],
    [/^ทุกไฟล์ต้องมีหมายเลขหน้า เช่น 1-3; 4-6$/, () => "Enter page ranges for every file, for example 1-3; 4-6."],
    [/^เสร็จแล้ว · (\d+) × (\d+) px · (.+)$/, (match) => `Done · ${match[1]} × ${match[2]} px · ${match[3]}`],
    [/^(.+) × (.+) px · (.+)$/, (match) => `${match[1]} × ${match[2]} px · ${match[3]}`],
    [/^ทำงานทุก (\d+) นาที$/, (match) => "Runs every " + match[1] + " minutes."],
    [/^นาที (.+) · ชั่วโมง (.+) · วันที่ (.+) ของเดือน$/, (match) => "Minute " + match[1] + " · hour " + match[2] + " · day " + match[3] + " of each month."],
    [/^นาที (.+) · ชั่วโมง (.+) · วันในสัปดาห์ (.+)$/, (match) => "Minute " + match[1] + " · hour " + match[2] + " · weekday " + match[3] + "."],
    [/^นาที (.+) · ชั่วโมง (.+) · ทำงานทุกวัน$/, (match) => "Minute " + match[1] + " · hour " + match[2] + " · runs every day."],
    [/^ทุก (\d+) นาที$/, (match) => "Every " + match[1] + " minutes."],
    [/^วันที่ (\d+) ของเดือน$/, (match) => "On day " + match[1] + " of each month."],
    [/^ในเดือน (\d+)$/, (match) => "In month " + match[1] + "."],
    [/^ในวันลำดับ (.+)$/, (match) => "On weekday " + match[1] + "."],
    [/^เวลา (\d{2}):(\d{2}) ทุกวันจันทร์ถึงศุกร์$/, (match) => "At " + match[1] + ":" + match[2] + " Monday through Friday."],
    [/^เวลา (\d{2}):(\d{2}) ทุกวัน$/, (match) => "At " + match[1] + ":" + match[2] + " every day."],
    [/^ทุกวันจันทร์ถึงศุกร์ เวลา (\d{2}):(\d{2})$/, (match) => "Runs Monday through Friday at " + match[1] + ":" + match[2] + "."],
    [/^วันที่ (\d+) ของเดือน เวลา (\d{2}):(\d{2})$/, (match) => "On day " + match[1] + " of each month at " + match[2] + ":" + match[3] + "."],
    [/^ในเดือน (\d+) เวลา (\d{2}):(\d{2})$/, (match) => "In month " + match[1] + " at " + match[2] + ":" + match[3] + "."],
    [/^ในวันลำดับ (.+) เวลา (\d{2}):(\d{2})$/, (match) => "On weekday " + match[1] + " at " + match[2] + ":" + match[3] + "."],
    [/^ข้อความสำเร็จ (\d+) หน้า$/, (match) => "Extracted text from " + match[1] + " pages."],
    [/^อ่านข้อความสำเร็จ (\d+) หน้า$/, (match) => "Extracted text from " + match[1] + " pages."],
    [/^รวมสำเร็จ (\d+) ไฟล์ · (\d+) หน้า$/, (match) => "Merged " + match[1] + " files · " + match[2] + " pages."],
    [/^บันทึกสำเร็จ (\d+) หน้า$/, (match) => "Saved " + match[1] + " pages."],
    [/^แยกสำเร็จ (\d+) ไฟล์$/, (match) => "Split into " + match[1] + " files."],
    [/^แปลงสำเร็จ (\d+) หน้า$/, (match) => "Converted " + match[1] + " pages."],
    [/^สร้าง PDF สำเร็จ (\d+) หน้า$/, (match) => "Created a PDF with " + match[1] + " pages."],
    [/^ใส่เลขหน้าสำเร็จ (\d+) หน้า$/, (match) => "Added page numbers to " + match[1] + " pages."],
    [/^ใส่ลายน้ำสำเร็จ (\d+) หน้า$/, (match) => "Added a watermark to " + match[1] + " pages."],
    [/^สร้าง Favicon (\d+) ขนาดและดาวน์โหลด ZIP แล้ว$/, (match) => "Created " + match[1] + " favicon sizes and downloaded the ZIP."],
    [/^อ่านข้อมูลสำเร็จ (\d+) หน้า$/, (match) => "Read metadata from a " + match[1] + "-page PDF."],
    [/^แปลงข้อมูลสำเร็จ (\d+) รายการ$/, (match) => "Converted " + match[1] + " items."],
    [/^กำลังเตรียมไฟล์\.\.\.$/, () => "Preparing file…"],
    [/^กำลังสร้างตัวอย่างหน้า\.\.\.$/, () => "Rendering page previews…"],
  ];
  for (const [pattern, replace] of patterns) {
    const match = key.match(pattern);
    if (match) return leading + replace(match) + trailing;
  }
  if (/[ก-๙]/u.test(key)) return leading + "This task could not be completed. Review the input and try again." + trailing;
  return leading + key + trailing;
}
